### PR TITLE
add a tmp dir for dat files

### PR DESCRIPTION
**Pull request by daedalus**
it will keep things more clean

### CODE REVIEW

**Comment by ReverseControl** [comment]
@daedalus I added YAFU as the default factoring software in the docker container, could you please try it out and test it? We can add this PR after that is working. Sorry for the delay, took me awhile to get YAFU working inside a docker container.

**Comment by daedalus** [comment]
Hi, as long as you merge my prs I will keep working on this project.

**Comment by ReverseControl** [comment]
@daedalus Sorry, been busy working on deadpool stuff.  Could you update this PR for the new structure of the repo. I still have to remove the msieve trunk. I will get to that this week.

**Comment by daedalus** [comment]
OK
PR #13 
Closing this.

**Pull request closed without merging**
